### ISSUE TITLE
Regarding some lil issues in the latest deployment

### ISSUE THREAD

**Issue by Jassi10000** [rohan-kulkarni-25/LGM-SOC#6]
@rohan-kulkarni-25 
## Buddy , this deployment is not working on mobile device and with that one of the last boxes is going out of the container , it would be nice to make this lil amendment to make you resource more beautiful , rest is very awesome 🎉

![Screenshot_20210612-154158_Chrome](https://user-images.githubusercontent.com/64856348/121772822-95e04280-cb95-11eb-82f8-ff1500ebaeb1.jpg)

**Comment by rohan-kulkarni-25** [comment]
Thanks a lot @Jassi10000  !! Have fixed it !!
